# Identidad del Sitio
title: Edna Daniela Trejo Martínez | Nanitre
email: contacto@nanitre.com
description: >-
  Nanitre es Daniela Trejo, artista. En este sitio encontrarás su portafolio de obra, un blog donde se documenta su proceso creativo y un registro de certificados de autenticidad que valida cada pieza. 
  Exploración visual, procesos creativos y verificación de autenticidad.

# Configuración de URLs
# Ajustado para que funcione en cafrhein.github.io/nanitre/
baseurl: ""
url: "https://nanitre.com"

# Configuración de Colecciones
collections:
  portfolio:
    output: true
    permalink: /obra/:title/
  posts:
    output: true
    permalink: /blog/:title/

# Ajustes de Build
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - bundle/

# Datos Personalizados
author:
  name: "Daniela Trejo"
  github: "danitrejo"
  instagram: "@nanitre.art"
